[tool.poetry]
name = "ynix_b"
version = "0.1.0"
description = "Web Server for Project_Ynix"
authors = ["Josh S Wilkinson <joshswilkinson@outlook.com>"]
packages = [
    { include = "ynix_b" }
]

[tool.poetry.dependencies]

python = "^3.10.6"
pendulum = "^2.1.2"
fastapi = "^0.79.0"
psycopg = "^3.0.16"
uvicorn = "^0.18.2"
python-dotenv = "^0.20.0"

[tool.poetry.scripts]
start_dev = 'ynix_b:main'
seed_dev = 'db:seed.py'
