[tool.poetry]
name = "ynix_b"
version = "0.1.0"
description = "Web Server for Project_Ynix"
authors = ["Josh S Wilkinson <joshswilkinson@outlook.com>"]
packages = [
    { include = "ynix_b" }
]

[tool.poetry.dependencies]
# last updated on 10.24.2022
python = "^3.10.6"
pendulum = "^2.1.2"
fastapi = "0.85.1"
psycopg = "^3.0.16"
uvicorn = "^0.18.2"
python-dotenv = "^0.20.0"

[tool.poetry.scripts]
start_dev = 'main:server.run()'
seed_dev = 'db:seed.py'
